# Generated by Django 3.2.22 on 2024-04-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Desc', models.CharField(db_column='Description', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Desc', models.CharField(db_column='Description', max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Reply', models.CharField(max_length=100)),
                ('Phno', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employeemate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('validity', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Validity', models.DateField()),
                ('Cardno', models.CharField(max_length=25)),
                ('Photo', models.CharField(max_length=100)),
                ('Rationcard', models.BigIntegerField()),
                ('Head', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jobcardmembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=300)),
                ('Age', models.IntegerField()),
                ('Relation', models.CharField(max_length=100)),
                ('Adharno', models.CharField(max_length=100)),
                ('Bank', models.CharField(max_length=100)),
                ('JOBCARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.CharField(max_length=100)),
                ('Desc', models.CharField(db_column='Description', max_length=100)),
                ('Photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scheme', models.CharField(max_length=100)),
                ('Desc', models.CharField(db_column='Description', max_length=100)),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wname', models.CharField(max_length=100)),
                ('Wnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Area', models.IntegerField()),
                ('Taxreciept', models.CharField(max_length=300)),
                ('JOBCARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobcard')),
                ('SCHEME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('JOBCARDMEMMBERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobcardmembers')),
                ('WORKREQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Wardmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.CharField(max_length=100)),
                ('Phno', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Photo', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('WARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ward')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=100)),
                ('Phno', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Photo', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Hname', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('District', models.CharField(max_length=100)),
                ('Sc', models.CharField(max_length=100)),
                ('Idproof', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('WARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100)),
                ('Phno', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Designation', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Planrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sdate', models.DateField()),
                ('Edate', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('MEMBER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wardmember')),
                ('PLAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Desc', models.CharField(db_column='Description', max_length=100)),
                ('Date', models.DateField()),
                ('PLANREQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.planrequest')),
                ('WARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Desc', models.CharField(db_column='Description', max_length=100)),
                ('Date', models.DateField()),
                ('WARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Jobcardrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Rationcard', models.BigIntegerField()),
                ('Head', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=300)),
                ('Idproof', models.CharField(max_length=300)),
                ('SCHEME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.scheme')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='jobcard',
            name='JOBCARDREQUEST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobcardrequest'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='Forwardedwrkrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPLOYEEMATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeemate')),
                ('WORKREQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workrequest')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeemateReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sslc', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('Status', models.CharField(max_length=100)),
                ('JOBCARDMEMBERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobcardmembers')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='employeemate',
            name='EMPLOYEEMATEREQ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeematereq'),
        ),
        migrations.AddField(
            model_name='employeemate',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('JOBCARDMEMBERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobcardmembers')),
            ],
        ),
        migrations.CreateModel(
            name='Deathregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=100)),
                ('Dist', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Dod', models.DateField()),
                ('Dob', models.DateField()),
                ('Wife', models.CharField(max_length=100)),
                ('Husband', models.CharField(max_length=100)),
                ('Hospital', models.CharField(max_length=100)),
                ('Regno', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
                ('CERTIFICATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Deathcertificaterequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Dcertificate', models.CharField(max_length=100)),
                ('DEATH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deathregistration')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='DEPARTMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.CreateModel(
            name='Birthregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=100)),
                ('Dist', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Mother', models.CharField(max_length=100)),
                ('Father', models.CharField(max_length=100)),
                ('Hospital', models.CharField(max_length=100)),
                ('Regno', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
                ('CERTIFICATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Birthcertificaterequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Bcertificate', models.CharField(max_length=100)),
                ('BIRTH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.birthregistration')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('EMPLOYEEMATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeemate')),
                ('JOBCARDMEMMBERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobcardmembers')),
                ('WORKREQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workrequest')),
            ],
        ),
    ]
